config/routes.rb
Rails.application.routes.draw do

	# API
  	namespace :api do
  		namespace :v1 do

  			# API INSERT

  		end
  	end

	root 'main#index'
	post '/',to: 'main#create'

	get '/access/logout',to: 'sessions#destory', as: 'logout'
	get '/access/normal',to: 'sessions#new', as: 'login'
	post '/access/normal',to: 'sessions#create'

	get 'angularjs/templates/:page',to: 'angularjs#index'

end

app/controllers/main_controller.rb
class MainController < ApplicationController

	skip_before_filter :authorize,:api_authorize
	
	def index

		if current_user.nil?

			@user = User.new if user_table
			
			render 'splash',layout: 'splash'

		else

			render

		end

	end

	def create

		@user = User.new params[:user]

		if @user.save

			session[:user_id] = @user.id

			redirect_to root_url,flash: {success: 'Thank you for signing up!'}

		else

			render 'splash',layout: 'splash'

		end

	end

end

app/views/main/splash.html.erb
<% if user_table %>
<%= form_for @user,url: root_url do |f| %>
  

  <% if @user.errors.any? %>
    
    <% @user.errors.full_messages.each do |message| %>

      <alert type="danger"><%= message %></alert>

    <% end %>

  <% end %>


  <div class="form-group">
    <%= f.text_field :email,class: 'form-control',placeholder: 'Email' %>
  </div>

  <div class="form-group">
    <%= f.password_field :password,class: 'form-control',placeholder: 'Password' %>
  </div>

  <div class="form-group">
    <%= f.password_field :password_confirmation,class: 'form-control',placeholder: 'Confirm Password' %>
  </div>

  <%= f.submit 'Sign Up',class: 'btn btn-default' %>


<% end %>
<%= link_to "Log In", login_path %>
<% end %>